# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
#relative_permalinks: true

# Setup
title:       Dan McCloy
tagline:     'Research Scientist (<a href="http://ilabs.washington.edu/" target="_blank">I-LABS</a>, <a href="http://www.washington.edu/" target="_blank">University of Washington</a>)'
description: 'Research Scientist, Institute for Learning and Brain Sciences, University of Washington'
url:         'http://dan.mccloy.info'
baseurl:     ''
paginate:    5

# About/contact
author:
  name:  Daniel McCloy
  orcid: 0000-0002-7572-3241
  url:   http://dan.mccloy.info
  email: drmccloy@uw.edu

# Custom vars
scholar:
  style:        ./bib/_apa-custom.csl
  locale:       en
  sort_by:      none
  order:        ascending
  source:       ./bib
  bibliography: McCloy_CV.bib

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "highlight", "strikethrough", "superscript"]

plugins: ['jekyll-paginate']
